---
abstract: 'extract CF values from email headers or body'
author:
  - 'This extension was originally written by Dirk Pape'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-ExtractCustomFieldValues
no_index:
  directory:
    - etc
    - inc
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 3.09
