abstract: RT Extension-ExtractCustomFieldValues Extension
distribution_type: module
generated_by: Module::Install version 0.64
license: unknown
name: RT-Extension-ExtractCustomFieldValues
no_index: 
  directory: 
    - etc
    - inc
    - t
version: 1.6
