--- 
abstract: RT Extension-ExtractCustomFieldValues Extension
author: ~
distribution_type: module
generated_by: Module::Install version 0.68
license: unknown
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: RT-Extension-ExtractCustomFieldValues
no_index: 
  directory: 
    - etc
    - html
    - po
    - var
    - inc
    - t
version: 1.8
